version: '2'

services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_HOST: localhost
      MYSQL_ROOT_PASSWORD: 4T3ASEQ1Eu3S
      MYSQL_DATABASE: db_ss
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d
    ports:
      - "127.0.0.1:3306:3306"
    healthcheck:
        test: ["CMD", 'mysqladmin', 'ping', '-p4T3ASEQ1Eu3S']
        timeout: 10s
        retries: 3

  nodejs:
    build:
      context: .
      dockerfile: Dockerfile.dockerfile
    ports:
      - "443:443"
    environment:
      MYSQL_HOST_IP: mysql
    volumes:
      - nodejs_data:/var/lib/nodejs
      - ./backend:/usr/src/app/backend
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysql_data:
  nodejs_data:


